import {test,expect} from '@playwright/test';
import {fileURLToPath} from 'node:url';
test('five-page settings, configuration, persistence and manual companion flow',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.pywebview={api:{bootstrap:async()=>({token:'ui-test-token'}),close:async()=>{}}};});
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'AI 模型（LLM）'})).toBeVisible();
 await expect(page.getByRole('navigation').getByRole('button')).toHaveCount(5);
 await page.getByRole('combobox',{name:'新增配置模板'}).selectOption('local');
 await page.getByRole('button',{name:'新增配置实例',exact:true}).click();
 await page.getByLabel('配置名称', {exact:true}).fill('本机测试模型');
 await page.locator('input[role=combobox]').fill('test-model');
 await page.getByRole('heading',{name:'AI 模型（LLM）'}).click();
 await page.getByRole('button',{name:'保存配置',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('模型配置已保存');
 await page.getByRole('button',{name:'设为当前模型',exact:true}).click();
 await page.getByRole('button',{name:'测试连接',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('连接测试通过');
 await page.getByRole('navigation').getByRole('button',{name:'VN 角色'}).click();
 await page.getByLabel('性格',{exact:true}).fill('安静、体贴，偶尔开个小玩笑。');
 await page.getByRole('button',{name:'保存设定'}).click();
 await expect(page.getByRole('status')).toContainText('VN 角色设定已保存');
 await page.screenshot({path:fileURLToPath(new URL('../../.runtime/settings-character.png',import.meta.url))});
 await page.reload();
 await expect(page.getByLabel('性格',{exact:true})).toHaveValue('安静、体贴，偶尔开个小玩笑。');
 await page.getByRole('navigation').getByRole('button',{name:'主动陪伴'}).click();
 await page.getByRole('button',{name:'立即触发一次'}).click();
 await expect(page.locator('blockquote')).toContainText('我在这里陪着你');
 await page.getByLabel('勿扰模式').check();
 await expect(page.locator('.workspace-top')).toContainText('所有设置已保存');
 await page.getByRole('navigation').getByRole('button',{name:'感知来源'}).click();
 await expect(page.getByRole('heading',{name:'感知来源'})).toBeVisible();
 await expect(page.getByLabel('屏幕截图视觉')).toBeDisabled();
 await page.getByRole('navigation').getByRole('button',{name:'发言气泡'}).click();
 await page.getByLabel('文字大小（像素）').fill('20');
 await page.getByLabel('文字大小（像素）').press('Tab');
 await expect(page.locator('.workspace-top')).toContainText('所有设置已保存');
 await page.getByRole('button',{name:'在桌宠旁预览'}).click();
 await expect(page.getByRole('status')).toContainText('预览气泡已显示');
 await page.screenshot({path:fileURLToPath(new URL('../../.runtime/settings-bubble.png',import.meta.url))});
 await page.reload();
 await expect(page.getByLabel('文字大小（像素）')).toHaveValue('20');
 expect(errors).toEqual([]);
});
